name: Validate Containerize

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the validation
        # The instructions say "Do not alter validate.sh", but that script tries to run a container in interactive mode, which doesn't work in CI. This modifies the script before running it, surfacing errors and running the container non-interatively.
        run: |
          cat validate.sh | \
          sed -e '1 a set -eo pipefail' -e 's/docker run -ti/docker run/' | \
          bash
        working-directory: containerize
