version: "3"
services:
  app:
    container_name: containerize_app_1
    build: app
    volumes:
      - ./app/src:/usr/src/app
  nginx:
    container_name: containerize_nginx_1
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    volumes:
      # "Ensure the SSL keypair is available to nginx, but is not baked in to the container image"
      - ./nginx/files/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./nginx/files/localhost.key:/etc/nginx/localhost.key:ro
