version: "3"
services:
  app:
    container_name: containerize_app_1
    build: app
    volumes:
      - ./app/src:/usr/src/app
    # "Allow local edits of the app source to be reflected in the running app container without restart (eg: hot code reload)" by using the development server
    environment:
      FLASK_APP: server
      FLASK_ENV: development
    command: flask run --host 0.0.0.0 --port 8000
  nginx:
    container_name: containerize_nginx_1
    build: nginx
    # "Nginx should accept requests on ports 80 and 443"
    ports:
      - "80:80"
      - "443:443"
    # "The `app` service should not reachable directly from the host and can only be accessed through the `nginx` service."
    links:
      - app
    volumes:
      # "Ensure the SSL keypair is available to nginx, but is not baked in to the container image"
      - ./nginx/files/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./nginx/files/localhost.key:/etc/nginx/localhost.key:ro
